fix(ci) new steps and summary generation

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,7 @@
 name: Django CI
 
 on:
+  workflow_call:
   push:
     branches: [main]
   pull_request:
@@ -8,7 +9,7 @@ on:
       - main
 
 jobs:
-  build-and-test:
+  validate:
     runs-on: ubuntu-latest
     services:
       postgres:
@@ -39,12 +40,47 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          python -m pip install --no-cache-dir poetry
-          poetry install
+          report=$(python -m pip install --no-cache-dir poetry && poetry install 2>&1) || true
+          exit_code=$?
+
+          if [ $? -ne 0 ]; then
+            echo "## ❌ Error installing dependencies" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
+
+      - name: Check code format
+        run: |
+          poetry run black --check .
+          report=$(poetry run black --check .) || true
+          exit_code=$?
+
+          if [ $? -ne 0 ]; then
+            echo "## ❌ Error installing dependencies" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
+
+      - name: Check code vulnerabilities
+        run: |
+          report=$(poetry run bandiit -r .) || true
+          exit_code=$?
+
+          if [ $? -ne 0 ]; then
+            echo "## ❌ Error installing dependencies" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
 
       - name: Run Tests
         env:
-          SECRET_KEY: "69tgugtg%^fgJO&*^"
+          SECRET_KEY: "fakesecretkey"
           DEBUG: False
           DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
           FRONTEND_BASE_URL: "http://localhost:3000"
@@ -55,11 +91,26 @@ jobs:
           MEILI_URL: "http://localhost:7700"
           MEILI_MASTER_KEY: "meilimasterkey"
         run: |
-          poetry run python manage.py test
+          report=$(poetry run python manage.py test) || true
+          exit_code=$?
 
-  deploy:
+          if [ $? -ne 0 ]; then
+            echo "## ❌ Error installing dependencies" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
+
+  # build-image:
+  #   runs-on: ubuntu-latest
+  #   needs: validate
+  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+  #   steps:
+
+  deploy-railway:
     runs-on: ubuntu-latest
-    needs: build-and-test
+    needs: validate
     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
     steps:
       - name: Install Railway
