Feat/ci improvements (#9)
* fix(ci) new steps and summary generation

* fix(ci): Fix summary headings

* fix(settings): code format

* fix(ci): exit_code validation

* fix(ci): bandit spelling

* fix(ci): rename job

* fix(ci): add missing pyproject and lock changes

* fix(ci): fix needs reference

* fix(pyproject): config bandit

* fix(ci): exit code verification

* fix(ci): exit code verification

* fix(ci): ref pyproject on bandit call

* fix(ci): pipe tee report

* fix(ci): pipe tee stderr

* feat(ci): Build image (ghcr)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,7 @@
 name: Django CI
 
 on:
+  workflow_call:
   push:
     branches: [main]
   pull_request:
@@ -8,7 +9,7 @@ on:
       - main
 
 jobs:
-  build-and-test:
+  validate-project:
     runs-on: ubuntu-latest
     services:
       postgres:
@@ -30,7 +31,8 @@ jobs:
           MEILI_NO_ANALYTICS: true
 
     steps:
-      - uses: actions/checkout@v6
+      - name: Checkout code
+        uses: actions/checkout@v6
 
       - name: Set up Python 3.14
         uses: actions/setup-python@v6
@@ -39,12 +41,52 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          python -m pip install --no-cache-dir poetry
-          poetry install
+          set +e
+          report=$(python -m pip install --no-cache-dir poetry 2>&1 && poetry install 2>&1 | tee /dev/stderr)
+          exit_code=$?
+          set -e
+
+          if [ $exit_code -ne 0 ]; then
+            echo "## ❌ Error installing dependencies" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
+
+      - name: Check code formatting
+        run: |
+          set +e
+          report=$(poetry run black --check . 2>&1 | tee /dev/stderr)
+          exit_code=$?
+          set -e
+
+          if [ $exit_code -ne 0 ]; then
+            echo "## ❌ Error checking code formatting" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
+
+      - name: Check code vulnerabilities
+        run: |
+          set +e
+          report=$(poetry run bandit -c pyproject.toml -r . 2>&1 | tee /dev/stderr)
+          exit_code=$?
+          set -e
+
+          if [ $exit_code -ne 0 ]; then
+            echo "## ❌ Error checking code vulnerabilities" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
 
       - name: Run Tests
         env:
-          SECRET_KEY: "69tgugtg%^fgJO&*^"
+          SECRET_KEY: "fakesecretkey"
           DEBUG: False
           DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
           FRONTEND_BASE_URL: "http://localhost:3000"
@@ -55,17 +97,81 @@ jobs:
           MEILI_URL: "http://localhost:7700"
           MEILI_MASTER_KEY: "meilimasterkey"
         run: |
-          poetry run python manage.py test
+          set +e
+          report=$(poetry run python manage.py test | tee /dev/stderr)
+          exit_code=$?
+          set -e
 
-  deploy:
+          if [ $? -ne 0 ]; then
+            echo "## ❌ Error installing dependencies" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$report" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit $exit_code
+          fi
+
+  build-image:
     runs-on: ubuntu-latest
-    needs: build-and-test
+    needs: validate-project
+    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+    steps:
+      - name: Install pipeline dependencies
+        run: pip install --no-cache-dir toml-cli
+
+      - name: Checkout code
+        uses: actions/checkout@v6
+
+      - name: Get version and generate tags
+        id: get-version-and-gen-tags
+        run: |
+          version=$(toml get project.version --toml-path pyproject.toml)
+          D='0|[1-9][0-9]*'
+          if [[ ! $version =~ ^($D)\.($D)\.($D)$ ]]; then
+            echo "## ❌ Error validating project version" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "Invalid version: $version" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
+          major="${BASH_REMATCH[1]}"
+          minor="$major.${BASH_REMATCH[2]}"
+          patch="$major.$minor.${BASH_REMATCH[3]}"
+
+          echo "major=$major" >> "$GITHUB_OUTPUT"
+          echo "minor=$minor" >> "$GITHUB_OUTPUT"
+          echo "patch=$patch" >> "$GITHUB_OUTPUT"
+
+      - name: Generate release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: gh release create ${{ steps.get-version-and-gen-tags.outputs.patch }} --latest
+
+      - name: Login to GHCR
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build image for tests
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          push: true
+          tags: |
+            ${{ github.repository_owner }}/getsongsweb-api:latest
+            ${{ github.repository_owner }}/getsongsweb-api:${{ steps.get-version-and-gen-tags.outputs.patch }}
+            ${{ github.repository_owner }}/getsongsweb-api:${{ steps.get-version-and-gen-tags.outputs.minor }}
+            ${{ github.repository_owner }}/getsongsweb-api:${{ steps.get-version-and-gen-tags.outputs.major }}
+
+  deploy-railway:
+    runs-on: ubuntu-latest
+    needs: build-image
     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
     steps:
       - name: Install Railway
         run: bash <(curl -fsSL cli.new)
-
-      - uses: actions/checkout@v6
 
       - name: Deploy
         run: railway up --service API
